int exec_IncDec                       (struct TreeNode *);
int CMP_node_logicValue               (struct TreeNode *);
struct TreeNode * exec_return         (struct TreeNode *);
int exec_FunctionCall                 (struct TreeNode *);
struct TreeNode * exec_functionScope  (struct TreeNode *);
struct TreeNode * exec_statement      (struct TreeNode *, char);
struct TreeNode * exec_scope          (struct TreeNode *, char);
void exec_Expression                  (struct TreeNode *);
void exec_DclN                        (struct TreeNode *);
void exec_Asgn                        (struct TreeNode *);
void exec_DclN_Asgn                   (struct TreeNode *);
void exec_Multi_DclN                  (struct TreeNode *);
void exec_Multi_Asgn                  (struct TreeNode *);
int exec_CMP                          (struct TreeNode *);
int exec_Operation                    (struct TreeNode *);
struct TreeNode * exec_while          (struct TreeNode *, char);
struct TreeNode * exec_ifElse         (struct TreeNode *, char);
struct TreeNode * exec_if             (struct TreeNode *, char);
